spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb'
    username: koo
    password: qwer1234
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

jwt:
  expiration_time: 259200000 #3일
  secret: cookiegodcookiegodcookiegodcookiegodcookiegodcookiegodcookiegodcookiegodcookiegodcookiegodcookiegodcookiegodcookiegodcookiegodcookiegodcookiegod