CREATE TABLE USER_INFO (
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   user_id VARCHAR(255) NOT NULL UNIQUE,
   name VARCHAR(30) NOT NULL,
   password VARCHAR(255) NOT NULL,
   id_type VARCHAR(20) NOT NULL,
   id_value VARCHAR(255) NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE QUOTE (
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   user_id BIGINT NOT NULL,
   code VARCHAR(20) NOT NULL,
   currency_code VARCHAR(10) NOT NULL,
   amount DOUBLE NOT NULL,
   fee DOUBLE NOT NULL,
   usd_exchange_rate DOUBLE NOT NULL,
   usd_target_amount DOUBLE NOT NULL,
   exchange_rate DOUBLE NOT NULL,
   target_amount DOUBLE NOT NULL,
   expire_time TIMESTAMP NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE'
);

ALTER TABLE QUOTE ADD CONSTRAINT FK_QUOTE_USER_INFO_ID FOREIGN KEY (user_id) REFERENCES USER_INFO(id) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE TRANSFER (
   id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   user_id BIGINT NOT NULL,
   quote_id BIGINT NOT NULL,
   requested_date TIMESTAMP NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE'
);

ALTER TABLE TRANSFER ADD CONSTRAINT FK_TRANSFER_USER_INFO_ID FOREIGN KEY (user_id) REFERENCES USER_INFO(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE TRANSFER ADD CONSTRAINT FK_TRANSFER_QUOTE_ID FOREIGN KEY (quote_id) REFERENCES QUOTE(id) ON UPDATE CASCADE ON DELETE CASCADE;